dist: trusty

language: go

go:
  - 1.8.3

os:
  - linux

install:
  - go get github.com/fatih/camelcase

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
